### ISSUE TITLE
How to access PlayerStorage inventory after disabling it as default

### ISSUE THREAD

**Issue by mahilo3550** [KidsDontPlay/PlayerStorage#1]
"I" button (which I made sure wasn't configured to any other mod/action) does nothing and any button I assign to "Player Storage - Open GUI" does nothing. Thing is, I wanna compare it with EnderUtilities' handy bag which is my current inventory but I need to be able to access both... How can I do this? Nothing in the config file helps this.

**Comment by KidsDontPlay** [comment]
very strange. It works for me fine.
does the log show some errors when you press the key?
Can you try it only with playerstorage and limelib installed?

**Comment by SDUBZ** [comment]
i just changed keybind in controls :) and it works for me when i use Rshift
