### ISSUE TITLE
Hdyra Boss broke my box

### ISSUE THREAD

**Issue by ExcitedName** [KidsDontPlay/PlayerStorage#17]
The Hydra boss from Twilight Forest hit the box with it's tail and bye bye. Is there a way to retrieve it via commands or something?

**Comment by KidsDontPlay** [comment]
which version do you use?

**Comment by ExcitedName** [comment]
oops sorry, I usually give those details in my bug reports.
Forge: 14.23.2.2611
PlayerStorage: 1.12.2-1.2.4
Twilight Forest 3.6.345

**Comment by KidsDontPlay** [comment]
playerstorage-1.12.2-1.2.5 will fix your problem

**Comment by ExcitedName** [comment]
Thank you much. This is a wonderful mod by the way. Thank you for everything you do for the Minecraft community.
