### ISSUE TITLE
Question: How can I revoke doomed items?

### ISSUE THREAD

**Issue by Knito58** [KidsDontPlay/PlayerStorage#19]
With the middle mouse click I configured some croparia fruit to min=0 max=0 and void.
Works! Yay. No more fruit from tall grass.

How can I change this back?

**Comment by KidsDontPlay** [comment]
mmh..
that's tricky. I never thought about this.
maybe you shouldn't have done that.
I'll think of something

**Comment by Knito58** [comment]
Maybe a new panel in the config where only the names of such doomed items/blocks are listed? With a reset button at each name?

Now I know I shouldn't have done this. But it is possible and gave me a very good feeling as it worked perfectly as intended.
