### ISSUE TITLE
Configured keys not working

### ISSUE THREAD

**Issue by Knito58** [KidsDontPlay/PlayerStorage#21]
The key for the standard GUI works when PS is set to replace the normal GUI with the PlayerStorage. But when it is "off" then neither the configured PS-Key for the PlayerStorage GUI nor the key for the Limitation GUI does anything for me.

Versions:

PlayerStorage 1.12.2-1.2.6
Forge 14.23.3.2668
MC 1.12.2 SSP

Edit: Now there seems to be no way to open the PlayerStorage GUI again. The playerstorage.cfg has no switch to change it back as the default players GUI. As the keys don't work I'm stuck.

**Comment by KidsDontPlay** [comment]
maybe it's an incompatibility with another mod

**Comment by Knito58** [comment]
That's possible. I have a lot of mods installed which I update as soon as new versions are available. Do you want a modlist? PlayerStorage is new for me and atm the only mod where the keys do not work.

I like PlayerStorage very much and already kicked another inventory mod because the concept and feeling of PlayerStorage is way better. I even plan to doom 2 other mods as soon as hotbar refilling is working.

I have started a new world because the PS already was very big and sucked up everything I gathered. My avatar was about to starve as the normal inventory did not receive any items. Luckily the default in a new world is vanilla GUI replacement. I'll not change this again in near future.

**Comment by KidsDontPlay** [comment]
the modlist would be nice.
is that a public modpack? that would be better. I don't want to download every mod manually

**Comment by Knito58** [comment]
Sorry. No public modpack atm. I'm still searching what mods I want on my server.
Still playing single player until I feel I have something that I can share with my friends and family.

[1.12]UncraftingTable-1.8-beta6.jar
ActuallyAdditions-1.12.2-r133.jar
ActuallyBaubles-1.12-1.1.jar
advInv-1.12.1-1.4.2.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
AoV-1.12-0.8.12.jar
Aroma1997Core-1.12.2-2.0.0.0.b148.jar
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b68.jar
AromaBackup-1.12.2-2.1.1.3.b98.jar
backpacks+1.12.2+-+3.4.4.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
Bookshelf-1.12.2-2.3.543.jar
buildcraft-7.99.16.jar
CD4017BE_lib-1.12.2-6.2.1.jar
ChestTransporter-1.12.2-2.8.8.jar
ChickenASM-1.12-1.0.2.7.jar
ChickenChunks-1.12.2-2.4.1.71-universal.jar
Chisel-MC1.12.2-0.2.0.31.jar
CodeChickenLib-1.12.2-3.1.6.339-universal.jar
Controlling-3.0.6.jar
Croparia-1.16.3.jar
crosshairmod-v0.8.2-forge-mc1.12.jar
CTM-MC1.12-0.2.3.12.jar
customstuff4-1.12.2-0.5.2.jar
cxlibrary-1.12.1-1.6.1.jar
CyclopsCore-1.12.2-0.11.5.jar
DarkUtils-1.12.2-1.8.208.jar
DoomlikeDungeons-1.11.1-MC1.12.2.jar
ElevatorMod-1.12.2-1.3.6.jar
EnderCore-1.12.2-0.5.20.jar
EnderIO-1.12.2-5.0.22.jar
EnderStorage-1.12.2-2.4.2.126-universal.jar
EverlastingAbilities-1.12.2-1.3.15.jar
ExCompressum_1.12.2-3.0.20.jar
exnihilocreatio-1.12-0.1.7.63.jar
extraalchemy-0.3.8.4-release.jar
extrautils2-1.12-1.7.6.jar
fluxnetworks-1.12.2-3.0.7.jar
Forgelin-1.6.0.jar
furnus-1.12.2-2.1.5.jar
generators-0.9.20.12-mc1.12.2.jar
GiacomosFishingNet-1.12.2-1.6.1.jar
GiacomosFoundry-1.12.2-1.3.13.jar
GravelMiner_1.12.1-6.1.2.jar
gravestone-1.10.1.jar
hopperducts-mc1.12-1.5.jar
InductiveLogistics-1.12.2-1.1.3.jar
inventorypets-1.12-1.4.9.9b.jar
InventoryTweaks-1.64-dev.jar
ironchest-1.12.2-7.0.42.827.jar
jei_1.12.2-4.9.0.163.jar
jeiintegration_1.12.2-1.5.1.36.jar
JustEnoughResources-1.12.2-0.8.7.41.jar
LaserLevel-1.12.2-2.1.0.19-universal.jar
leafdecay-1.0.0.2-mc1.12.2.jar
limelib-1.12.2-1.7.10.jar
LLOverlayReloaded-1.1.4-mc1.12.jar
lostcities-1.12-2.0.7.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
malisiscore-1.12.2-6.4.0.jar
malisisdoors-1.12.2-7.3.0.jar
malisisswitches-1.12.2-5.1.0.jar
mcjtylib-1.12-2.6.7.jar
MCMultiPart-2.5.0.jar
MinersAdvantage-1.12.2-1.3.14.189.jar
MobGrindingUtils-0.3.5.jar
ModernLights-1.0.3_1.12.jar
MoreFurnaces-1.12.2-1.10.4.jar
NaturesCompass-1.12.2-1.5.1.jar
Neat 1.4-15.jar
nomoreglowingpots-1.0.jar
NoMoreRecipeConflict-0.9(1.12).jar
notenoughwands-1.12-1.6.1.jar
omlib-1.12.2-3.0.0-140.jar
ompd-1.12.2-3.0.0-35.jar
openmodularturrets-1.12.2-3.0.0-243.jar
OptiFine_1.12.2_HD_U_D1.jar
Placebo-1.12.2-1.3.3.jar
playerstorage-1.12.2-1.2.6.jar
pressure-1.3.1.9-mc1.12.2.jar
quacklib-2.1.1.jar
RandomThings-MC1.12.2-4.1.5.jar
RebornCore-1.12.2-3.7.5.259-universal.jar
RebornStorage-1.12.2-3.0.4.39.jar
reconstructor-2.11a.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
RefinedRelocation_1.12.2-4.2.20.jar
refinedstorage-1.5.32.jar
Repurpose-1.0.0.13.jar
rftools-1.12-7.33.jar
rftoolsctrl-1.12-1.8.1.jar
rftoolsdim-1.12-5.53.jar
rswires-3.0.0.jar
Ruins-1.12.2.jar
Schematica-1.12.2-1.8.0.168-universal.jar
sensorcraft-1.12.2-0.6.2.jar
sonarcore-1.12.2-5.0.7.jar
TamModized-1.12.1-0.15.5.jar
theoneprobe-1.12-1.4.22.jar
topaddons-1.12-0.15.0.jar
torchmaster_1.12.2-1.6.1.53.jar
transprot-1.12.2-1.5.2.jar
TrashSlot_1.12.1-8.4.6.jar
VTweaks-1.12.2-1.4.12b.jar
waterfreefarming-2.0.5.jar
Waystones_1.12.2-4.0.33.jar
Wither+Skeleton+Tweaks-1.12.2-2.5.0.jar
WTS-1.1.0.jar
Xaeros_Minimap_1.14.9.1_Forge_1.12.jar
XaerosWorldMap_1.2.3_Forge_1.12.jar
xnet-1.12-1.6.9.jar

**Comment by KidsDontPlay** [comment]
can you zip your mods and upload them somewhere?

**Comment by KidsDontPlay** [comment]
to continue playing you can use NBTExplorer.
change `playerdata/<playerUUID>/Forge Caps/playerstorage:inventory/defaultGUI` to 1

**Comment by Knito58** [comment]
NBTExplorer: I can change the value. Save it. Close NBTExplorer and load it again: It is set to "1". But when loading the world, the vanilla GUI is opening. After shutting down MC and watching the file again, the defaultGUI setting is 0 again. I did this multiple times to ensure I do it correctly.

I'm gonna pack my mods in a zip, along with the config files as well. Give me an hour.

**Comment by Knito58** [comment]
https://www.dropbox.com/s/ia3719ocv40l89p/knito58-mods.zip?dl=0

**Comment by Knito58** [comment]
PlayerStorage 1.12.2-1.2.7

Yay! Fix confirmed. Now the world is playable again. But...

Thaumcraft for 1.12.2 is out just now and I think about starting over again...

From my view this issue can be closed.
