### ISSUE TITLE
Three crashes lately....

### ISSUE THREAD

**Issue by Knito58** [KidsDontPlay/PlayerStorage#24]
MC 1.12.2, Forge 14.23.3.2698, LimeLib 1.7.12, Playerstorage 1.2.10

The last: When killing a shulker in the End. https://pastebin.com/LUPc1s5C

Before there were two other crashes: Eating the first of two Iron apples near a lot of items in the End. 
The first: Opening my Player Storage grave block in the End.

For the first two events yesterday night there I only found one crash report:

https://pastebin.com/edAggZVH

**Comment by KidsDontPlay** [comment]
please update to latest version and send me new crash reports if they happen

**Comment by Knito58** [comment]
Sorry didn't get the update notice in time. Please close this one.
