### ISSUE TITLE
Ticking Player Exception

### ISSUE THREAD

**Issue by Knito58** [KidsDontPlay/PlayerStorage#28]
Forge 14.23.3.2698, PlayerStorage 1.3.2

Was flying around the base (angel ring xu2) and dismantled some surplus xnet cables to hide them in the base structure with the "facade" block of xnet. The exception fired when I broke a normal blue cable while flying. Which is not a problem most of the time.

https://pastebin.com/13grHWxx

**Comment by KidsDontPlay** [comment]
That's very weird. Actually this crash is impossible. But obviously it isn't.
I added more information to the crash. So the bug is not fixed, but when it happens again, the crash report will be more helpful

**Comment by Knito58** [comment]
Yep the crashing conditions are not met most of the time and after that crash report I did the same things again without changing anything and did not crash again. Some more conditions which were "on":

- it rained but rain was blocked with the rain shield (random things)
- Miner's Advantage had set the Captivation Ability (=Magnetize, get all Items in 16 block range) on

Sorry sometimes I feel as if I attract impossible things.

**Comment by Knito58** [comment]
Closing this because it seems to be fixed - did not happen anymore.
