### ISSUE TITLE
Ticking Player Exception

### ISSUE THREAD

**Issue by Knito58** [KidsDontPlay/PlayerStorage#29]
Did start a new world and destroyed  a dirt block with a shovel. The PlayerStorage inventory was nearly full but I was expanding my tiny dirt base with cobble from strip mining, so there should have been about 200 space freed up again when the game crashed. The PS Inv was still on initial size.

https://pastebin.com/nsVa3KBR

MC 1.12, Forge 14.23.4.2738, PlayerStorage 1.3.3

And now something completely different:

The item refill option which I only found today when starting freshly and setting the PS option is great! It works always when the player uses up items from the hotbar. When a stack (ie torches) is depleated by another mod (MinersAdvantage / Illuminator) then it won't refill. This is not a bug report about the refill, only an info.

**Comment by KidsDontPlay** [comment]
is that a modpack I can download somewhere?

**Comment by Knito58** [comment]
No Sir. I export the mod folder, the config folder and the crash-report folder for you.
https://www.dropbox.com/s/u0edch4r0058ytl/konitor-pack.zip?dl=0
120.076.398 Bytes

**Comment by KidsDontPlay** [comment]
Sorry bothering you again. 
please try [this](https://drive.google.com/open?id=1nG4mTxYJZWsY2wa1vXM3qbj-tEnffTaV) and show me the crash report when it happens next time

**Comment by Knito58** [comment]
Installed and running. But I also updated some other mods, also MinersAdvantage, which claims to have changed some behaviour and which was my favourite suspect in this case. We'll see. Maybe it does not happen again.

**Comment by Knito58** [comment]
Clicked on the "clear grid" button in PS to remove the five leftover oak planks after crafting 37 chests with all planks I had in storage. (shift-clicked to craft them) This is not "ticking player" but "no such element".
https://pastebin.com/sKJznNWN

MC 1.12.2, Forge 14.23.4.2738, PS 1.3.3 (the "this" version).

Edit: After a restart it crashed again when using the clear grid button. This time I saw that there was a freshly crafted tripwire hook clued to the mouse pointer when clicking on the button. The error now is "updating screen events".

https://pastebin.com/2TyxHZmB

**Comment by KidsDontPlay** [comment]
please open a new issue for that

**Comment by Knito58** [comment]
Ticking Player Exception:

Was in the End and just killed a "Reinforced Enderman" which had blue particles on him which indicated that he carried a (superb) totem of "Everlasting Abilities". 

https://pastebin.com/ZX6h2QTK

**Comment by KidsDontPlay** [comment]
this crash has nothing to do with the other problem.
please open a new issue
the description (like 'Ticking Player') is irrelevant. Relevant is the stacktrace

**Comment by Knito58** [comment]
I believe this is solved. No crash for months.
