### ISSUE TITLE
Clear Grid Button gives Exceptions

### ISSUE THREAD

**Issue by Knito58** [KidsDontPlay/PlayerStorage#30]
Clicked on the "clear grid" button in PS to remove the five leftover oak planks after crafting 37 chests with all planks I had in storage. (shift-clicked to craft them) This is not "ticking player" but "no such element".
https://pastebin.com/sKJznNWN

MC 1.12.2, Forge 14.23.4.2738, PS 1.3.3 (the "this" version).

Edit: After a restart it crashed again when using the clear grid button. This time I saw that there was a freshly crafted tripwire hook clued to the mouse pointer when clicking on the button. The error now is "updating screen events".

https://pastebin.com/2TyxHZmB

**Comment by Knito58** [comment]
Another one with the clear grid button: https://pastebin.com/vnJ13T7U
Fresh world and I cleared a stone pickaxe from the GUI crafting table. Clearing recipes sometimes works with a little hesitating moment. Sometimes it crashes. Most times it works as expected.

This time it is "index out of bounds" and it tells that if the index is 2 and the size of the array is "2" then the index would address a not existing 3. element - when the array is 0 based.

MC 1.12.2, Forge 14.23.4.2745, PS 1.3.5

**Comment by Knito58** [comment]
Sometimes the clear grid button does not clear the whole recipe. Ie the pickaxe will have the sticks left in the grid.

**Comment by Knito58** [comment]
Same as above in new world with galacticraft:  https://pastebin.com/4e1tNuvZ

MC 1.12.2, Forge 14.23.4.2745, PS 1.3.5

**Comment by Knito58** [comment]
Had opened the GUI freshly. Wanted to craft something. There were leftovers from last craft in the crafting table. They did not form a valid recipe anymore.
Clear Grid Button clicked. This thime it is "No Such Element".
https://pastebin.com/uGWhs6a1

I want to state that the clear grid buttons works fine most times. It seems to be 1 : 30 (roughly estimated) chance for invoking an exception.

MC 1.12.2, Forge 14.23.4.2745, PS 1.3.5

**Comment by KidsDontPlay** [comment]
It's really hard to fix a bug that occurs only 1:30. So I cannot reproduce it.
and different kinds of exception don't make it easier to figure out the cause.
furthermore it seems that you are the only one with that problem, which indicates a mod incompatibility

**Comment by Knito58** [comment]
Yes that is true. I have no standard modpack and am still searching the mods for my LAN server. And somehow I seem to attract issues from mods. It's a talent. :(
You are not the only one suffering strange issues reported by me. I agree that finding such bug is really hard under that conditions. In my opinion a mod should work under all conditions and not only if it is wrapped into a standard modpack. I hope you agree in that point.

Atm PlayerStorage is within the error log messages but there is more. The finally failing routine is from Java itself. Somehow lists become invalid while the button is clicked. It seems to be a sync problem.

**Comment by KidsDontPlay** [comment]
I totally agree with you. but if a mod is badly written or does things it shouldn't do, I can't do anything to prevent that.

**Comment by Knito58** [comment]
Did not get any exception when using the clear grid button a long time with 1.3.6. I believe this is fixed now.
