### ISSUE TITLE
Faster Crafting

### ISSUE THREAD

**Issue by Thiana** [KidsDontPlay/PlayerStorage#39]
Any chance you cold apply the same fix [Fast Workbench](https://minecraft.curseforge.com/projects/fastworkbench?gameCategorySlug=mc-mods&projectID=288885) does? Shift click 3x3 crafting is really slow without it.

Thanks.

**Comment by KidsDontPlay** [comment]
the fix is already done. It feels slow because it has to scan the entire inventory. a vanilla workbench don't do that.
