### ISSUE TITLE
Suggestion(1.12.2) oredict derp

### ISSUE THREAD

**Issue by SDUBZ** [KidsDontPlay/PlayerStorage#4]
a little quality of life thing for new users when in fluid  storage can you make a word or little tool tip to say bucket needed for new users i had many people spam click it and it crash them 

when i was trying to craft something with wood/stone needed it tries to use cobble when shift click function for recipes with jei

Forge: 1.12.2-2515
ps: 1.12.2-1.0.4
jei: 1.12.2- 4.8.0.110

**Comment by KidsDontPlay** [comment]
please use interpunction!!

it should be obvious that you need a bucket (or other container) to transport fluids.
a crashlog would be very helpful.
I can't reproduce your problem with jei shift click function.
