### ISSUE TITLE
More a question than an issue unless this is considered one

### ISSUE THREAD

**Issue by DatrixTHLK** [KidsDontPlay/PlayerStorage#43]
Does the playerstorage usually not work unless you break it and then replace it back in the same area after you login to the game each time? For a little while now the playerstorage block works when I place it first on the ground next to a hopper, but when I close out of the game and then log back into the same save game the hoppers connected to the playerstorage block keep the inventory within the hoppers and don't get sucked into the player storage block unless I break the player storage blocks and place them back on the ground.

Not sure If I explained it good enough let me know if I didn't.

Minecraft: 1.12.2
Forge: 14.23.4.2759
Player Storage: 1.3.6

**Comment by KidsDontPlay** [comment]
that's definitely a bug. I'll look into it

**Comment by DatrixTHLK** [comment]
Ah, I see. Thanks for looking into it! I appreciate the response also. :)

**Comment by DatrixTHLK** [comment]
Hi again MrRiegel,

 I like this mod but I found a couple issues besides the same one I mentioned with the 1.3.6 version. I mentioned this in a video since I thought it be best to show the example while explaining the issue.
https://youtu.be/txFhTC_sFdQ

Minecraft: 1.12.2
Forge: 14.23.4.2765
Player Storage: 1.3.7

I'm not sure if you are still looking into this already seeing as you have mentioned earlier that you are. If you are, then you may ignore. Hopefully the video can be seen.

**Comment by KidsDontPlay** [comment]
the visual bug is fixed.
do you play on a dedicated server?

**Comment by DatrixTHLK** [comment]
Nope, I play online, single player only.

**Comment by KidsDontPlay** [comment]
That's weird. It works for me.
Are there any crashes in your log file when you enter the world?

**Comment by DatrixTHLK** [comment]
No, but there is a lot of errors within the FML log that would be considered crash issues if Vanillafix wasn't in my mods list (they aren't considered critical). I'm going to take a look at the FML log now and see what I can find out. I'm getting a lot of spam since my world is going from 40fps to 4 fps in a matter of an hour. I'll let you know if I find anything.

Edit (8:28pm): It turns out the spam came from Journeymap. I've mentioned this in the issues page for Journeymaps team. However, this might not have fixed the issue so I'm going to test it to see if removing the mod fixed the issue with player storage.

Re-Edit (8:45pm): That didn't fix the visual bug.

**Comment by DatrixTHLK** [comment]
Issue has been fixed in 1.4.8. Thanks again!
