### ISSUE TITLE
Does not respect keepInventory

### ISSUE THREAD

**Issue by kit-sunei** [KidsDontPlay/PlayerStorage#48]
drops inventory even when gamerule is on

notes
- playing on server
- double checked gamerule
- still places in block and thus does not lose entire inventory

**Comment by KidsDontPlay** [comment]
there is a config option to disable the block and keep the storage instead.

**Comment by kit-sunei** [comment]
misread the keeper setting in config, closing

**Comment by kit-sunei** [comment]
ah oops page didnt refresh, thanks tho!
