### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Xogue** [KidsDontPlay/PlayerStorage#5]
The mod is amazing, and it is a wonder I havent seen something like this before. nice work!  ;)

I would like to see if you would add an option to not have the search box have focus when entering the inventory. More often than not, I dont want to search for anything, and I need my keys for other things.

thanks for the consideration

**Comment by KidsDontPlay** [comment]
thanks :blush:
Are you going to make a mod spotlight for this mod? (I read you message on discord)

**Comment by Xogue** [comment]
I could make one for it if you wanted. The reason I know about it is that I added it to my pack (I had to scale the apples, and change/remove recipes to make it fit into my pack better)

but let me know if that is something you would like and ill get on it soon ;)

**Comment by KidsDontPlay** [comment]
Would be nice if you do that. If you have any questions, go for it.

**Comment by Xogue** [comment]
I can get to it.   will be a bit though, I have a couple others that requested one.  You mentioned you saw my message in discord, but mrRiegel isn't a name there, are you called something else on that server?

would be easier to talk there if you wanna send me a private message or friend request or something. just lemme know its you if you decide to do that. I dont accept random requests. i get enough of those as it is, lol
