### ISSUE TITLE
Search Does Not Include Enchantments

### ISSUE THREAD

**Issue by ghost** [KidsDontPlay/PlayerStorage#50]
Mod version: 1.12.2-1.3.9

When searching for the title of an enchantment, such as "fortune", any items with the enchantment, including enchanted books, are not included in the results. This also leads to mismatches when syncing with JEI's search.

**Comment by KidsDontPlay** [comment]
try `#fortune`

**Comment by ghost** [comment]
Oops, sorry for not catching that. Closing, then.
