### ISSUE TITLE
Reset of Limits needed

### ISSUE THREAD

**Issue by Knito58** [KidsDontPlay/PlayerStorage#52]
I have limitations that "eat" some ingredients. I.E. the "Iron Casing" of Actually Additions vanishes. As it seems to be set to "Void" and/or "Max = 0" there never is a stack in the inventory. So I never can change this setting to a working state again.

Thats why a list of "Limitation settings" is needed and the possibility to delete some entries.

PS 1.12.2-1.3.10, Forge 14.23.5.2770

**Comment by KidsDontPlay** [comment]
see the question mark bottom left in the GUI

**Comment by Knito58** [comment]
Yep. It sais "Hover over an item". No item. No stack. Nothing to hover over.
Nothing to do do save his live, call his wife in....

**Comment by KidsDontPlay** [comment]
well, if you don't have an item to insert (iron casing in your case), where is the problem?

**Comment by Knito58** [comment]
I insert it. It vanishes. Cannot reconfigure because no stack. "Hover over an item" means it needs an item to hover over. But there is none. There will never be one of that type. After setting it to zero it gets eaten away. My fault. Shouldn't have done that. But did it. Now I beg for a list of configured items to be able to delete some entries.

:/

**Comment by Knito58** [comment]
The mistake is clearly on MY side. I configured something because I could. Now I want to scull backwards. But there is no way back.

**Comment by KidsDontPlay** [comment]
you can hover over any item in your inventory. not just the player storage

**Comment by Knito58** [comment]
Oh my god! Sorry for that! I was always one too high.
Great!
Will close this issue. Thank you.
