### ISSUE TITLE
Keybinding set for this mod never saves

### ISSUE THREAD

**Issue by mahilo3550** [KidsDontPlay/PlayerStorage#9]
Minecraft: 1.12.2
Forge: 1.12.2-14.23.1.2610
LimeLib: 1.12.2-1.7.9
PlayerStorage: 1.12.2-1.1.1

Every time I start up Minecraft I have to fix the keybindings for this and one other mod. With this mod, the "Open GUI" keybind always resets to the "APPS" key (between Alt & Ctrl to the right of the space bar). I don't know why this happens, especially when I remove the keybinding and leave both empty. The "APPS" key WAS being used by another mod until now because I removed it. Hopefully it won't happen anymore, but I'll let you know what happens.

**Comment by Knito58** [comment]
For me it is every time I load a world then the keybindings are overwritten with the default keys. Which already are used for something else in my config.

Minecraft 1.12.2
Forge 14.23.3.2676
LimeLib 1.12.2-1.7.10
PlayerStorage 1.12.2-1.2.8
